//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBH.Lotte.Project.Services.MemberServicesSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MemberServicesSvc.IMemberSvc")]
    public interface IMemberSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberSvc/CheckAuthenticate", ReplyAction="http://tempuri.org/IMemberSvc/CheckAuthenticateResponse")]
        string CheckAuthenticate(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberSvc/CheckAuthenticate", ReplyAction="http://tempuri.org/IMemberSvc/CheckAuthenticateResponse")]
        System.Threading.Tasks.Task<string> CheckAuthenticateAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberSvc/GetMemberByToken", ReplyAction="http://tempuri.org/IMemberSvc/GetMemberByTokenResponse")]
        BBH.Lotte.Domain.MemberBO GetMemberByToken(string token, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberSvc/GetMemberByToken", ReplyAction="http://tempuri.org/IMemberSvc/GetMemberByTokenResponse")]
        System.Threading.Tasks.Task<BBH.Lotte.Domain.MemberBO> GetMemberByTokenAsync(string token, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberSvc/GetMemberByEmail", ReplyAction="http://tempuri.org/IMemberSvc/GetMemberByEmailResponse")]
        BBH.Lotte.Domain.MemberBO GetMemberByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberSvc/GetMemberByEmail", ReplyAction="http://tempuri.org/IMemberSvc/GetMemberByEmailResponse")]
        System.Threading.Tasks.Task<BBH.Lotte.Domain.MemberBO> GetMemberByEmailAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberSvcChannel : BBH.Lotte.Project.Services.MemberServicesSvc.IMemberSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberSvcClient : System.ServiceModel.ClientBase<BBH.Lotte.Project.Services.MemberServicesSvc.IMemberSvc>, BBH.Lotte.Project.Services.MemberServicesSvc.IMemberSvc {
        
        public MemberSvcClient() {
        }
        
        public MemberSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckAuthenticate(string email, string pass) {
            return base.Channel.CheckAuthenticate(email, pass);
        }
        
        public System.Threading.Tasks.Task<string> CheckAuthenticateAsync(string email, string pass) {
            return base.Channel.CheckAuthenticateAsync(email, pass);
        }
        
        public BBH.Lotte.Domain.MemberBO GetMemberByToken(string token, string email) {
            return base.Channel.GetMemberByToken(token, email);
        }
        
        public System.Threading.Tasks.Task<BBH.Lotte.Domain.MemberBO> GetMemberByTokenAsync(string token, string email) {
            return base.Channel.GetMemberByTokenAsync(token, email);
        }
        
        public BBH.Lotte.Domain.MemberBO GetMemberByEmail(string email) {
            return base.Channel.GetMemberByEmail(email);
        }
        
        public System.Threading.Tasks.Task<BBH.Lotte.Domain.MemberBO> GetMemberByEmailAsync(string email) {
            return base.Channel.GetMemberByEmailAsync(email);
        }
    }
}
